### ISSUE TITLE
Health checks created with terraform, do not work.

### ISSUE THREAD

**Issue by zeroflaw** [terraform-providers/terraform-provider-consul#124]
I'm having some issues when using the consul terraform provider using health checks. They don't seem to be working correctly. However if I create them from the standard API they do work. So It must be something that's not correct in the terraform json payload.
I'm still trying to find out exactly what the case is, but this is my current setup.

### Terraform Version
Terraform v0.12.2

### Affected Resource(s)
Please list the resources as a list, for example:
- consul_service

### Terraform Configuration Files
```
provider "consul" {
  address    = "http://172.20.0.2:8500"
  datacenter = "dc1"
}

resource "consul_node" "compute1" {
  name    = "compute"
  address = "http://172.19.0.7"
}

resource "consul_service" "myservice1" {
  name       = "${consul_node.compute1.name}"
  node       = "${consul_node.compute1.name}"
  port       = 80

  check {
    check_id = "service:compute1"
    name = "Compute health check"
    notes = "Script based health check"
    http = "http:/172.19.0.7"
    interval = "10s"
    timeout = "2s"
  }

  tags    = ["primary", "v1"]
}
```

### Expected Behavior
Health Checks: 'Service checks and Node checks' on Consul UI to contain output in the little black window.

### Actual Behavior
No health checks are performed by consul.

Note: 
If I create a service & health check with the following payload, everything works correctly. 

```
{
  "ID": "compute1",
  "Name": "compute",
  "Tags": [
    "primary",
    "v1"
  ],
  "Address": "172.19.0.7",
  "Port": 80,
  "Meta": { "version": "1" },
  "EnableTagOverride": false,
  "Check": {
    "HTTP": "http://172.19.0.7",
    "Interval": "10s"
  },
  "Weights": {
    "Passing": 10,
    "Warning": 1
  }
}
```

```
 curl \
    --request PUT \ 
    --data @payload.json \
    http://172.20.0.2:8500/v1/agent/service/register

```
### Steps to Reproduce
1. Setup Consul
2. Use terraform config above
3. `terraform apply`
4. See that health checks are created but don't actually run/work.

### Important Factoids
running consul in vagrant **ubuntu/bionic64**
```
docker-compose file:
version: '3'

services:

  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -client=0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client=0.0.0.0"

  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client=0.0.0.0"

  health:
    image: nginxdemos/hello
    networks:
      - consul-demo
    ports:
      - "80:80"

networks:
  consul-demo:
```
